name: Merge to main branch

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  TF_INPUT: false

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  TF_VAR_S3_KEY: ${{ secrets.S3_KEY }}

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=$TF_VAR_S3_BUCKET_NAME" -backend-config="key=$TF_VAR_S3_KEY" -backend-config="region=$AWS_REGION"

      - name: apagar depois
        id: apagardepois
        run: cat .terraform.lock.hcl

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
