name: Push commits

on:
  push:
    branches:
      - '*'
      - '!main'

env:
  TF_LOG: INFO
  TF_INPUT: false

  TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  TF_VAR_S3_KEY: ${{ secrets.S3_KEY }}

jobs:
  push_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform lint
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        if: success() || failure() # Run even if formatting fails
        run: terraform validate -no-color
